#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int ampm_text_color = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int blue = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int blue_focused = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int calendar_header = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int calendar_selected_date_text = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int circle_background = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int dark_gray = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int darker_blue = 2131165191;
			
			// aapt resource value: 0x7f070018
			public const int date_picker_selector = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int date_picker_text_disabled = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int date_picker_text_normal = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int date_picker_view_animator = 2131165194;
			
			// aapt resource value: 0x7f070019
			public const int date_picker_year_selector = 2131165209;
			
			// aapt resource value: 0x7f07000b
			public const int done_disabled_dark = 2131165195;
			
			// aapt resource value: 0x7f07001a
			public const int done_text_color = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int done_text_color_dark = 2131165211;
			
			// aapt resource value: 0x7f07000c
			public const int done_text_color_dark_disabled = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int done_text_color_dark_normal = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int done_text_color_disabled = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int done_text_color_normal = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int light_gray = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int line_background = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int line_dark = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int neutral_pressed = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int numbers_text_color = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int red = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int red_focused = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int transparent_black = 2131165207;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050005
			public const int ampm_label_size = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ampm_left_padding = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int date_picker_component_width = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int date_picker_header_height = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int date_picker_header_text_size = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int date_picker_view_animator_height = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int day_number_select_circle_radius = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int day_number_size = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int dialog_height = 2131034112;
			
			// aapt resource value: 0x7f05001f
			public const int done_button_height = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int done_label_size = 2131034144;
			
			// aapt resource value: 0x7f050012
			public const int extra_time_label_margin = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int footer_height = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int header_height = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int left_side_width = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int minimum_margin_sides = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int minimum_margin_top_bottom = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int month_day_label_text_size = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int month_label_size = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int month_list_item_header_height = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int month_list_item_padding = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int month_list_item_size = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int month_select_circle_radius = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int picker_dimen = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int selected_calendar_layout_height = 2131034140;
			
			// aapt resource value: 0x7f050002
			public const int selected_date_day_size = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int selected_date_month_size = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int selected_date_year_size = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int separator_padding = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int time_label_right_padding = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int time_label_size = 2131034124;
			
			// aapt resource value: 0x7f05001d
			public const int year_label_height = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int year_label_text_size = 2131034142;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int done_background_color = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int done_background_color_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int ampm_hitspace = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int ampm_label = 2131230739;
			
			// aapt resource value: 0x7f080007
			public const int animator = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int button1 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int button2 = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int center_view = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int date_picker_day = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int date_picker_header = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int date_picker_month = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int date_picker_month_and_day = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int date_picker_year = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int day_picker_selected_date_layout = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int done = 2131230720;
			
			// aapt resource value: 0x7f080018
			public const int done_button = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int hour_space = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int hours = 2131230735;
			
			// aapt resource value: 0x7f080017
			public const int line = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int minutes = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int minutes_space = 2131230736;
			
			// aapt resource value: 0x7f080019
			public const int month_text_view = 2131230745;
			
			// aapt resource value: 0x7f08000e
			public const int separator = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int textView1 = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int time_display = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int time_display_background = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int time_picker = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int time_picker_dialog = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int date_picker_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int date_picker_done_button = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int date_picker_header_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int date_picker_selected_date = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int date_picker_view_animator = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int time_header_label = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int time_picker_dialog = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int year_label_text_view = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001b
			public const int ApplicationName = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int Hello = 2130968602;
			
			// aapt resource value: 0x7f04000c
			public const int ampm_circle_radius_multiplier = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int circle_radius_multiplier = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int circle_radius_multiplier_24HourMode = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int day_of_week_label_typeface = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int day_picker_description = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int deleted_key = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int done_label = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hour_picker_description = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int item_is_selected = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int minute_picker_description = 2130968581;
			
			// aapt resource value: 0x7f04000f
			public const int numbers_radius_multiplier_inner = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int numbers_radius_multiplier_normal = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int numbers_radius_multiplier_outer = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int radial_numbers_typeface = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int sans_serif = 2130968595;
			
			// aapt resource value: 0x7f040006
			public const int select_day = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int select_hours = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int select_minutes = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int select_year = 2130968585;
			
			// aapt resource value: 0x7f040014
			public const int selection_radius_multiplier = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int text_size_multiplier_inner = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int text_size_multiplier_normal = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int text_size_multiplier_outer = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int time_placeholder = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int time_separator = 2130968601;
			
			// aapt resource value: 0x7f04000a
			public const int year_picker_description = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int ampm_label = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int day_of_week_label_condensed = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int done_button_light = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int time_label = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int time_label_thin = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
